### ISSUE TITLE
Declaration file missing 

### ISSUE THREAD

**Issue by HarishVJ** [abelalvarez89/xlsx-parse-json#2]
Could not find a declaration file for module 'xlsx-parse-json'. 'c:/Workings/...../node_modules/xlsx-parse-json/index.js' implicitly has an 'any' type.
  Try `npm install @types/xlsx-parse-json` if it exists or add a new declaration (.d.ts) file containing `declare module 'xlsx-parse-json';`

**Comment by abelalvarez89** [comment]
npm install xlsx-parse-json or yarn add xlsx-parse-json should do the trick. Maybe you have something cached. Im using that package in different applications written in Angular Js, Angular 4 and React without any issues. Can you provide more details on the problem you are having.
