### ISSUE TITLE
Wrong conversion of dates

### ISSUE THREAD

**Issue by jonelrecto** [abelalvarez89/xlsx-parse-json#6]
i have a date in excel july 1, 2018
then when i convert it to json the output is 43282 in date integer
when i convert it into new Date the output is Jan 01 1970

**Comment by abelalvarez89** [comment]
I will look into it, will reply with an answer soon

**Comment by abelalvarez89** [comment]
@jonelrecto sorry for the delay, I uploaded a fix to this issue https://github.com/abelalvarez89/xlsx-parse-json/commit/ce32278c483937c0a0e929c3d7bb190ef7e76203

**Comment by morozovkirill** [comment]
I have similar issue.

I have dates in exel file like: "18.05.2018  9:50:00". But after parsing it converts into "43238.40972222222".
