### ISSUE TITLE
how can i get the sheets list if i have lutiple sheets in my xlsx file?

### ISSUE THREAD

**Issue by TechNov** [abelalvarez89/xlsx-parse-json#9]
how can i get the sheets list if i have lutiple sheets in my xlsx file?

**Comment by abelalvarez89** [comment]
I have a sample app where it shows how the output will look. Try https://abelalvarez.info/xlsx-parse-json/ also if you can provide a sample of the xlsx you are using. You will get an array in json each new entry is a new sheet
